# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: midimessage.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "PortDescription" do
    optional :direction, :enum, 1, "PortDescription.Direction"
    optional :name, :string, 2
    optional :create_dynamic, :bool, 3
    optional :key, :int32, 4
  end
  add_enum "PortDescription.Direction" do
    value :IN, 0
    value :OUT, 1
    value :INOUT, 2
  end
  add_message "PortList" do
    repeated :ports, :message, 1, "PortDescription"
  end
  add_message "PublishedMessage" do
    optional :topic, :string, 1
    optional :sender, :string, 2
    optional :message, :bytes, 3
  end
  add_message "SubscribeRequest" do
    optional :topic, :string, 1
    optional :requestNode, :string, 2
    optional :is_subscription, :bool, 3
  end
  add_message "MessageMetadata" do
    optional :port, :uint32, 1
    optional :host, :string, 2
    optional :friendly_name, :string, 3
    optional :is_master, :bool, 4
    optional :software_package, :string, 5
    optional :software_version, :string, 6
    optional :ports, :message, 7, "PortList"
  end
  add_message "Error" do
    optional :error_type, :string, 1
    optional :severity, :enum, 2, "Error.ErrorSeverity"
  end
  add_enum "Error.ErrorSeverity" do
    value :DEPRECATION, 0
    value :WARNING, 1
    value :ERROR, 2
    value :CATASTROPHE, 3
  end
  add_message "MidiData" do
    optional :channel, :uint32, 1
    optional :data, :bytes, 2
  end
  add_message "MidiMessage" do
    optional :message_id, :string, 1
    optional :last_message, :string, 2
    optional :message_type, :enum, 5, "MidiMessage.MessageTypes"
    oneof :payload do
      optional :message_metadata, :message, 6, "MessageMetadata"
      optional :error, :message, 7, "Error"
      optional :midi_data, :message, 8, "MidiData"
      optional :acked_message, :string, 9
      optional :ports, :message, 10, "PortList"
      optional :published_message, :message, 11, "PublishedMessage"
      optional :subscribe_request, :message, 12, "SubscribeRequest"
    end
  end
  add_enum "MidiMessage.MessageTypes" do
    value :HOST_ANNOUNCE, 0
    value :HOST_RETIRE, 1
    value :RESEND_REQUESTED, 2
    value :ERROR, 3
    value :MIDI_DATA, 4
    value :ACK, 5
    value :PORT_REQUEST, 6
    value :PUBLISHED_MESSAGE, 7
    value :SUBSCRIBE_REQUEST, 8
  end
end

PortDescription = Google::Protobuf::DescriptorPool.generated_pool.lookup("PortDescription").msgclass
PortDescription::Direction = Google::Protobuf::DescriptorPool.generated_pool.lookup("PortDescription.Direction").enummodule
PortList = Google::Protobuf::DescriptorPool.generated_pool.lookup("PortList").msgclass
PublishedMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("PublishedMessage").msgclass
SubscribeRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("SubscribeRequest").msgclass
MessageMetadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("MessageMetadata").msgclass
Error = Google::Protobuf::DescriptorPool.generated_pool.lookup("Error").msgclass
Error::ErrorSeverity = Google::Protobuf::DescriptorPool.generated_pool.lookup("Error.ErrorSeverity").enummodule
MidiData = Google::Protobuf::DescriptorPool.generated_pool.lookup("MidiData").msgclass
MidiMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("MidiMessage").msgclass
MidiMessage::MessageTypes = Google::Protobuf::DescriptorPool.generated_pool.lookup("MidiMessage.MessageTypes").enummodule
